modLoader="javafml"
loaderVersion="[43,)"
license="GNU LGPL 3.0"
[[mods]]
modId="kubejsdelight"
version="${file.jarVersion}"
displayName="KubeJSDelight"
authors="QinomeD, Bob Varioa"
description='''
FD integration for KubeJS
'''
[[dependencies.kubejsdelight]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kubejsdelight]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kubejsdelight]]
   modId="kubejs"
   mandatory=true
   versionRange="[1902.6.0-build.282,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kubejsdelight]]
   modId="farmersdelight"
   mandatory=true
   versionRange="[1.19-1.2.1,)"
   ordering="NONE"
   side="BOTH"