modLoader="javafml"
loaderVersion="[47,)"
license="GNU LGPL 3.0"
[[mods]]
modId="kubejsdelight"
version="${file.jarVersion}"
displayName="KubeJSDelight"
authors="QinomeD, Bob Varioa"
description='''
FD integration for KubeJS
'''
[[dependencies.kubejsdelight]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kubejsdelight]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kubejsdelight]]
   modId="kubejs"
   mandatory=true
   versionRange="[2001.6.4-build.95,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.kubejsdelight]]
   modId="farmersdelight"
   mandatory=true
   versionRange="[1.20.1-1.2.3,)"
   ordering="NONE"
   side="BOTH"